function [ PRs, mask ] = PRscore( proposals, label, pixlMap )
% Compute the PR score for each proposal generated by gop.
% INPUT:
% - proposals: The proposals generated by gop
% - label: The oversegmentation label of the image. The Minimum value of
% label is 0;
% *** Note that the label and the proposals are related to each others. Both of them are generated by gop algorithm
% - pixlMap: the pixel wise saliency map of the image.
% 
% OUTPUT:
% -  PRs: the Precision-Recall score of the input proposals with respect to
% the input pixel level saliency map.

%% Generate the pixel-wise map for each proposals
pNum = size(proposals, 1);
label = label + 1;
[h, w] = size(label);
mask = zeros(h, w, pNum);

for pId = 1:pNum
    m = proposals(pId,:);
    mask(:, :, pId) = double(m( label ));
end
%% Calculate precision Pre and Recall Rc;
hitMap = bsxfun(@times, mask, pixlMap);
hit = sum(sum(hitMap));
hit = reshape(hit, pNum, 1);
pOp = sum(sum(mask));
pOp = reshape(pOp, pNum, 1);
salOp = sum(pixlMap(:));
Pre = hit./pOp;
Rc = hit/salOp;
% PRs = (1+0.3)*Pre.*Rc./(0.3*Pre+Rc);
PRs = Pre.*Rc;
end
